# Generated by Django 5.2.18 on 2026-10-09 09:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comparable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("make", models.CharField(max_length=60)),
                ("model", models.CharField(max_length=80)),
                ("trim", models.CharField(max_length=80)),
                ("mileage", models.PositiveIntegerField()),
                ("price_cents", models.PositiveBigIntegerField()),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("source_url", models.URLField(max_length=1000, unique=True)),
                ("observed_at", models.DateTimeField()),
                ("approved", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=120)),
                ("url", models.URLField(max_length=1000)),
                ("year", models.PositiveIntegerField()),
                ("make", models.CharField(max_length=60)),
                ("model", models.CharField(max_length=80)),
                ("trim", models.CharField(max_length=80)),
                ("vin", models.CharField(blank=True, max_length=17)),
                ("mileage", models.PositiveIntegerField()),
                ("price_cents", models.PositiveBigIntegerField()),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("condition", models.CharField(max_length=20)),
                ("details", models.TextField(blank=True)),
                ("seller_phone", models.CharField(blank=True, max_length=18)),
                ("observed_at", models.DateTimeField()),
                ("active", models.BooleanField(default=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("new", "New Lead"),
                            ("contacted", "Contacted"),
                            ("negotiation", "Negotiation"),
                            ("acquired", "Acquired"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("count", models.PositiveIntegerField(default=0)),
                ("window", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("url", models.URLField(blank=True, max_length=1000)),
                ("token_env", models.CharField(blank=True, max_length=100)),
                ("enabled", models.BooleanField(default=False)),
                (
                    "authority",
                    models.TextField(
                        help_text="Permission/license or public feed terms reviewed by the owner."
                    ),
                ),
                ("last_success", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Suppression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=18, unique=True)),
                ("reason", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Audit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=80)),
                ("reference", models.CharField(max_length=150)),
                ("detail", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Consent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=18, unique=True)),
                ("evidence", models.TextField()),
                ("granted_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("blocked", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Outbox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("sms", "SMS"), ("crm", "CRM")], max_length=10
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("payload", models.JSONField()),
                ("status", models.CharField(default="queued", max_length=20)),
                ("provider_id", models.CharField(blank=True, max_length=120)),
                ("error", models.CharField(blank=True, max_length=250)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(null=True)),
                ("finished_at", models.DateTimeField(null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="scout.listing"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactLock",
            fields=[
                (
                    "phone",
                    models.CharField(max_length=18, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="scout.outbox"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="listing",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="scout.source"
            ),
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("payload", models.JSONField()),
                ("digest", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("applied_at", models.DateTimeField(null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="scout.source"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="outbox",
            index=models.Index(
                fields=["status", "created_at"], name="scout_outbo_status_3cd19a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="outbox",
            constraint=models.UniqueConstraint(
                fields=("listing", "kind", "revision"), name="one_outbox_per_revision"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["make", "model", "year"], name="scout_listi_make_538176_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["stage", "active"], name="scout_listi_stage_6d66ea_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.UniqueConstraint(
                fields=("source", "external_id"), name="listing_source_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(
                condition=models.Q(("price_cents__gt", 0)),
                name="positive_listing_price",
            ),
        ),
    ]
